//! Tensor-product cubic B-spline interpolation.
//!
//! The regular-grid implementation stores one B-spline coefficient tensor with
//! the same shape and C-style memory order as the input values. Coefficients are
//! generated by applying a one-dimensional tridiagonal solve along each axis.

pub mod rectilinear;
pub mod regular;

pub use rectilinear::MultiBsplineRectilinear;
pub use regular::MultiBsplineRegular;

// `usize::max` is not const-stable on this MSRV, so use a local helper in
// const scratch-sizing methods.
#[cfg(feature = "par")]
pub(crate) const fn max_usize(a: usize, b: usize) -> usize {
    if a > b { a } else { b }
}

#[derive(Clone, Copy, PartialEq)]
pub(crate) enum Saturation {
    None,
    InsideLow,
    OutsideLow,
    InsideHigh,
    OutsideHigh,
}
