name: release-rust

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
  workflow_dispatch:

jobs:

  test_rust:
    uses: ./.github/workflows/test-rust.yml

  test_python:
    # Don't release a rust crate version that breaks the python bindings
    uses: ./.github/workflows/test-python.yml

  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    needs: [test_rust, test_python]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
